#Import lexer class to the parser
from lexer import Scanner

# Parser class to parse the tokens generated by the Scanner
class Parser:
    def __init__(self, text):
        self.scanner = Scanner(text)
        self.next()

    # Print error message and exit if expected symbol is not found
    def expected(self, symbols):
        print(f"Error at Line: {self.scanner.line} Column: {self.scanner.col} Expected one of {symbols} but found '{self.csym}'")
        exit()
    
    # Get next token from scanner and update current symbol
    def next(self):
        self.scanner.next()
        self.csym = self.scanner.kind()

    # Consume token if matches otherwise raise syntax error 
    def match(self,symbol):
        if self.csym == symbol:
            self.next()
        else:
            self.expected([symbol])
    
    # Validates the top-level Program structure: 'program' ID ':' Body '.'
    def program(self):
        self.match("program")
        self.match("ID")
        self.match(":")
        self.body()
        self.match(".")

    # Validates the Body structure: {Declartaions} Statements
    def body(self):
        if self.csym == "bool" or self.csym == "int":
            self.declarations()
        self.statements()

    # Validates a sequence of one or more declaration blocks
    def declarations(self):
        self.declaration()
        while self.csym == "bool" or self.csym == "int":
            self.declaration()

    # Validates a single Declaration: (Bool | Int) ID {',' ID} ';' 
    def declaration(self):
        assert self.csym == "bool" or self.csym == "int"
        self.next()
        self.match("ID")
        while self.csym == ",":
            self.next()
            self.match("ID")
        self.match(";")
    
    # Validates a sequence of Statements separated by semicolons
    def statements(self):
        self.statement()
        while self.csym == ";":
            self.next()
            self.statement()
    
    # Validates a Statement is one of: Assignment, If, While, or Print
    def statement(self):
        if self.csym == "ID":
            self.assignment()
        elif self.csym == "if":
            self.if_statement()
        elif self.csym == "while":
            self.while_statement()
        elif self.csym == "print":
            self.print_statement()
        else:
            self.expected(["ID", "if", "while", "print"])
    
    # Validates that an Assignment Follows ID ':=' Expression
    def assignment(self):
        self.match("ID")
        self.match(":=")
        self.expression()
    
    # Validates an If Statement follows 'if' Expression 'then' Body ['else' Body] 'end'
    def if_statement(self):
        assert self.csym == "if"
        self.match("if")
        self.expression()
        self.match("then")
        self.body()
        if self.csym == "else":
            self.next()
            self.body()
        self.match("end")

    # Validates a While Statement follows 'while' Expression 'do' Body 'end'
    def while_statement(self):
        assert self.csym == "while"
        self.match("while")
        self.expression()
        self.match("do")
        self.body()
        self.match("end")

    # Validates a Print Statement follows 'print' Expression
    def print_statement(self):
        assert self.csym == "print"
        self.match("print")
        self.expression()
    
    # Validates an Expression follows: SimpleExpression [ RelOperator SimpleExpression ]
    def expression(self):
        self.simple_expression()
        if self.csym in ["=", "!=", "<", ">", ">=", "=<"]:
            self.next()
            self.simple_expression()
    
    # Validates a SimpleExpression follows Term {AddOperator Term}
    def simple_expression(self):
        self.term()
        while self.csym in ["+", "-", "or"]:
            self.next()
            self.term()

    # Validates a Term follows Factor {MulOperator Factor}  
    def term(self):
        self.factor()
        while self.csym in ["*", "/", "and", "mod"]:
            self.next()
            self.factor()
    
    # Validates a Factor follows: [ UnaryOperator ] (Literal | Identifier | "(" Expression ")" )
    def factor(self):
        if self.csym in ["-","not"]:
            self.next()
        if self.csym == "NUM" or self.csym in ["true", "false"]:
            self.literal()
        elif self.csym == "ID":
            self.match("ID")
        elif self.csym == "(":
            self.next()
            self.expression()
            self.match(")")
        else:
            self.expected(["NUM", "true", "false", "ID", "(", "-", "not"])

    # Validates a Literal is either a int literal or a Bool literal
    def literal(self):
        assert self.csym in ["NUM", "true", "false"]
        if self.csym == "NUM":
            self.match("NUM")
        else:
            self.bool_lit()
    
    # Validates a Boolean Literal is either 'true' or 'false'
    def bool_lit(self):
        assert self.csym in ["true", "false"]
        self.next()


# Get text file and parse 
if __name__ == "__main__":
    file_name = input("Enter the name of the text file: ")
    with open(file_name, 'r') as file:
        content = file.read()
    parser = Parser(content)
    parser.program()
    print("true")